### ISSUE TITLE
data.json als JSON Array anstelle eines einzelnen JSON Objekts

### ISSUE THREAD

**Issue by eddex** [FlashJunior/swisstubers.info#1]
Hallo Martin

Als ich mit den Daten etwas ausprobieren wollte, fiel mir auf, dass es sich bei der `data.json` Datei um ein einzelnes, grosses JSON Objekt handelt. Das Objekt verfügt über einzelne Properties (bzw. wieder Objekte) für die Channels. Jetz ist aber das Problem, dass diese Daten so nicht leicht geparsed und verwendet werden können.  Ich weiss nicht wie du das auf [swisstubers.info](https://swisstubers.info) machst, aber um im JSON Objekt auf ein Property zugreifen zu können muss man dessen Namen kennen.

# Jetziger Zustand

Beispiel:

```JSON
{
    "CHANNELID1": {
        "NAME": "Bob"
    },
    "CHANNELID2": {
        "NAME": "Alice"
    }
}
```

Wenn ich nun das JSON Objekt habe, und auf die Daten eines Channels zugreifen will, muss ich das folgendermassen tun:

```javascript
data.CHANNELID1.NAME // Bob
data.CHANNELID2.NAME // Alice
```

Ich muss also die Channel Id eines jeden Channels bereits im voraus kennen.

# Verbesserungvorschlag

Durch das ändern in eine Liste von "Channel Objekten" können die Daten als Liste gleicher Objekte verwendet werden.
```JSON
[
     {
        "id": "CHANNELID1",
        "NAME": "Bob"
     },
     {
        "id": "CHANNELID2",
        "NAME": "Alice"
    },
]
```
So können die Daten viel besser verarbeitet werden.
```javascript
data[0].NAME // Bob
data[1].NAME // Alice

// oder in einer schleife
for d in data:
    print(d.NAME)
```

Noch ein grosses Danke für das bereitstellen der Daten hier auf Github! Ich hoffe du hast mal Zeit dir das anzuschauen.  ✌️

**Comment by FlashJunior** [comment]
Beide json files werden automatisch generiert via [serializejson](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-s/serializejson.html). Aktuell investiere ich keine Zeit in das Projekt, sorry.

**Comment by eddex** [comment]
Umgesetzt in badd976. Danke @FlashJunior! 👍
